declare module "google-it";
declare module "google-news-json";
declare module "search-engine-client";
declare module "googlethis";
declare module "google-news-scraper";
declare module "jsonwebtoken";
declare module "cherio";
declare module "google-news-scraper.js";
declare module "newspaperjs";